### ISSUE TITLE
Support Serverless V2

### ISSUE THREAD

**Issue by WillBeebe** [massdriver-cloud/aws-aurora-serverless-postgres#15]
Aurora Serverless V2 offers a lot of benefits, among them better scaling.

**Comment by coryodaniel** [comment]
V2 is a substantially different service and there is _not_ a direct upgrade path from v1. It will probably be implemented as an new bundle.

v1 is "serverless" ... v2 is a provisioned cluster with a "db.serverless" instance type.

Migration from v1 to v2 includes
* snapshotting v1
* creating new provisioned rds cluster of the same version as v1
* restoring snapshot
* upgrade new cluster to desired version that supports 'db.serverless' instances
* change instance type of new cluster to 'db.serverless'

**Comment by coryodaniel** [comment]
supported by [aws aurora postgresql bundle](https://github.com/massdriver-cloud/aws-aurora-postgresql/blob/main/massdriver.yaml#L868)
